#!/usr/bin/env python3
"""Render bench/results/*.json into a Markdown report.

    uv run python bench/render.py                        # -> bench/BASELINE.md
    uv run python bench/render.py --out bench/FINAL.md \
        --baseline bench/results                         # -> bench/FINAL.md

`--baseline` adds a "Baseline to final" section computed from a second results
directory (median against median, straight from the JSON). The tables themselves
are identical either way; only the title, the profile lookups (they key on
function names, which survive edits, unlike line numbers) and the delta section
change.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bench.common import BENCH_DIR, RESULTS_DIR, load_json, machine_info

ORDER = ["kml_100", "kml_1000", "kml_10000", "shp_1000"]

# E2E noise band from bench/AB_PIPELINE.md: deltas inside it are not signal.
NOISE_BAND = {"kml_1000": 0.05, "kml_10000": 0.04, "shp_1000": 0.11}


def fmt(value: float, digits: int = 3) -> str:
    return f"{value:,.{digits}f}"


def band(s: dict, digits: int = 3) -> str:
    return (f"{fmt(s['min'], digits)} / {fmt(s['median'], digits)} / "
            f"{fmt(s['max'], digits)}")


def mb(value: float) -> str:
    return f"{value / 1_000_000:,.1f}"


def short_site(text: str) -> str:
    """`File "/long/path/x.py", line 12` -> `x/y.py:12`."""
    text = text.replace(str(Path.home() / ".local/share/uv"), "<uv>")
    text = text.replace(str(BENCH_DIR.parent) + "/", "")
    text = text.replace('File "', "").replace('", line ', ":")
    return text.strip().rstrip('"')


_MISSING = object()


def find(rows: list[dict], needle: str, default: object = _MISSING) -> dict | None:
    """First profile row whose name contains `needle`, e.g. `(measure)`.

    `default` (may be None) replaces the KeyError when the row is absent.
    """
    for row in rows:
        if needle in row["name"]:
            return row
    if default is not _MISSING:
        return default  # type: ignore[return-value]
    raise KeyError(needle)


def pkg_version(name: str) -> str:
    try:
        return version(name)
    except PackageNotFoundError:
        return "not installed"


def delta(base: float, final: float) -> str:
    return f"{(final - base) / base * 100:+.1f}%"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(BENCH_DIR / "BASELINE.md"))
    parser.add_argument("--title", default="Baseline profile")
    parser.add_argument("--baseline", default=None,
                        help="results directory of the run to compare against")
    args = parser.parse_args()

    http = load_json(RESULTS_DIR / "http.json")
    proc = load_json(RESULTS_DIR / "process.json")
    # C extensions named in the memory narrative: shapely shows up in older profiles.
    extensions = ("shapely, pyproj, libexpat"
                  if any("shapely" in row["name"]
                         for row in proc["profile"]["kml_10000"]["top12"])
                  else "pyproj, libexpat")
    manifest = load_json(Path("/tmp/geo-bench-fixtures/manifest.json"))
    info = machine_info()
    base_http = base_proc = None
    if args.baseline:
        base_http = load_json(Path(args.baseline) / "http.json")
        base_proc = load_json(Path(args.baseline) / "process.json")
    out: list[str] = []

    def add(line: str = "") -> None:
        out.append(line)

    add(f"# {args.title}")
    add()
    add(f"Generated by `bench/render.py` from `{RESULTS_DIR}` on "
        f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}.")
    add()
    add("All latencies are best-of-5 (or best-of-3 for RSS) reported as "
        "`min / median / max`. Times in seconds use three decimals, milliseconds two.")
    add()

    # --- machine -------------------------------------------------------------
    add("## Machine")
    add()
    add("| item | value |")
    add("| --- | --- |")
    add(f"| uname | `{info['uname']}` |")
    add(f"| machine | {info['machine']} |")
    add(f"| python | {info['python']} (`{info['python_executable']}`) |")
    add(f"| cpu count | {info['cpu_count']} |")
    add(f"| fastapi / pyproj / pyshp | {pkg_version('fastapi')} / "
        f"{pkg_version('pyproj')} / {pkg_version('pyshp')} |")
    add()

    # --- fixtures ------------------------------------------------------------
    add("## Fixtures")
    add()
    add("Written by `bench/gen_fixtures.py` to `/tmp/geo-bench-fixtures/`. KML mix: "
        "40% polygons, 40% lines, 20% points, all inside one UTM zone. A Shapefile "
        "holds one geometry type per file, so `shp_1000` is 1,000 polygons.")
    add()
    add("| fixture | format | features | file size |")
    add("| --- | --- | ---: | ---: |")
    for name in ORDER:
        entry = manifest[name]
        add(f"| `{name}` | {entry['kind']} | {entry['features']:,} | "
            f"{entry['size_bytes']:,} bytes ({entry['size_bytes'] / 1_000_000:.2f} MB) |")
    add()

    # --- cold start ----------------------------------------------------------
    add("## Cold start")
    add()
    add("Process spawn to `GET /api/health/` returning 200, fresh temp `GEO_DATA_DIR` "
        "and `GEO_DATABASE` per run, 5 runs, real uvicorn on 127.0.0.1:8123.")
    add()
    add("| min (s) | median (s) | max (s) |")
    add("| ---: | ---: | ---: |")
    cold = http["cold_start_s"]
    add(f"| {fmt(cold['min'])} | {fmt(cold['median'])} | {fmt(cold['max'])} |")
    add()

    # --- upload --------------------------------------------------------------
    add("## Upload latency: POST /api/files/")
    add()
    add("Real HTTP to uvicorn, includes multipart encoding of the whole file on the "
        "client and writing it to disk.")
    add()
    add("| fixture | min (ms) | median (ms) | max (ms) |")
    add("| --- | ---: | ---: | ---: |")
    for name in ORDER:
        s = http["fixtures"][name]["upload_ms"]
        add(f"| `{name}` | {fmt(s['min'], 2)} | {fmt(s['median'], 2)} | {fmt(s['max'], 2)} |")
    add()

    # --- end to end ----------------------------------------------------------
    add("## End to end: upload to status COMPLETED")
    add()
    add("The real work: parse, reproject, measure, store JSON. HTTP column polls "
        "`GET /api/files/{id}/` every 5 ms against uvicorn; in-process column runs the "
        "same flow through `fastapi.testclient` (no socket, no uvicorn).")
    add()
    add("| fixture | features | HTTP min (s) | HTTP median (s) | HTTP max (s) | "
        "in-process median (s) | pipeline only, median (s) |")
    add("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for name in ORDER:
        s = http["fixtures"][name]["e2e_s"]
        add(f"| `{name}` | {manifest[name]['features']:,} | {fmt(s['min'])} | "
            f"{fmt(s['median'])} | {fmt(s['max'])} | "
            f"{fmt(proc['inproc'][name]['e2e_s']['median'])} | "
            f"{fmt(proc['rss'][name]['process_s']['median'])} |")
    add()

    # --- GET endpoints -------------------------------------------------------
    add("## GET /api/files/{id}/")
    add()
    add("| fixture | min (ms) | median (ms) | max (ms) |")
    add("| --- | ---: | ---: | ---: |")
    for name in ORDER:
        s = http["fixtures"][name]["info_ms"]
        add(f"| `{name}` | {fmt(s['min'], 2)} | {fmt(s['median'], 2)} | {fmt(s['max'], 2)} |")
    add()

    meas = http["measurements_10k"]
    add("## GET /api/files/{id}/measurements/ (10,000-feature file)")
    add()
    add(f"Response body: **{meas['bytes']:,} bytes** "
        f"({meas['bytes'] / 1_000_000:.2f} MB), served as stored JSON text.")
    add()
    add("| min (ms) | median (ms) | max (ms) | bytes |")
    add("| ---: | ---: | ---: | ---: |")
    add(f"| {fmt(meas['ms']['min'], 2)} | {fmt(meas['ms']['median'], 2)} | "
        f"{fmt(meas['ms']['max'], 2)} | {meas['bytes']:,} |")
    add()

    # --- RSS -----------------------------------------------------------------
    add("## Peak memory during processing")
    add()
    add("Each fixture processed in its own process, 3 runs, RSS sampled every 10 ms "
        "(`ps`), cross-checked against `getrusage`. Baseline is RSS after imports, "
        "before `process_file` runs.")
    add()
    add("| fixture | baseline RSS (MB) | peak RSS (MB) | rusage peak (MB) | "
        "growth over baseline (MB) | MB per 1,000 features |")
    add("| --- | ---: | ---: | ---: | ---: | ---: |")
    for name in ORDER:
        r = proc["rss"][name]
        base = r["baseline_rss_bytes"]["median"]
        peak = r["peak_rss_bytes"]["median"]
        grow = peak - base
        per_k = grow / 1_000_000 / r["features"] * 1000
        add(f"| `{name}` | {mb(base)} | {mb(peak)} | {mb(r['peak_rusage_bytes']['median'])} | "
            f"{mb(grow)} | {per_k:,.1f} |")
    add()

    # --- throughput ----------------------------------------------------------
    add("## Throughput")
    add()
    add("`features/s (HTTP)` uses the median end-to-end HTTP time, so it includes "
        "upload and status polling. `features/s (pipeline)` uses only `process_file` "
        "in a dedicated process.")
    add()
    add("| fixture | features | features/s (HTTP) | features/s (pipeline) | "
        "ms per feature (HTTP) | ms per feature (pipeline) |")
    add("| --- | ---: | ---: | ---: | ---: | ---: |")
    for name in ORDER:
        feats = manifest[name]["features"]
        http_s = http["fixtures"][name]["e2e_s"]["median"]
        pipe_s = proc["rss"][name]["process_s"]["median"]
        add(f"| `{name}` | {feats:,} | {feats / http_s:,.0f} | {feats / pipe_s:,.0f} | "
            f"{http_s * 1000 / feats:.3f} | {pipe_s * 1000 / feats:.3f} |")
    add()

    # --- concurrency ---------------------------------------------------------
    conc = http["concurrency"]["concurrent"]
    serial = http["concurrency"]["serial"]
    add("## Concurrency: 8 uploads of `kml_1000`")
    add()
    add("Concurrent: all 8 requests issued from 8 threads at the same instant. "
        "Serial: 8 requests one after another. Both then wait for their own file to "
        "reach COMPLETED.")
    add()
    add("| mode | wall time for all 8 (s) | upload latency median (ms) | "
        "upload latency range (ms) | e2e median (s) | e2e range (s) |")
    add("| --- | ---: | ---: | ---: | ---: | ---: |")
    for label, entry in (("concurrent (8 threads)", conc), ("serial", serial)):
        add(f"| {label} | {fmt(entry['wall_s'])} | "
            f"{fmt(entry['upload_ms']['median'], 2)} | "
            f"{fmt(entry['upload_ms']['min'], 2)} - {fmt(entry['upload_ms']['max'], 2)} | "
            f"{fmt(entry['e2e_s']['median'])} | "
            f"{fmt(entry['e2e_s']['min'])} - {fmt(entry['e2e_s']['max'])} |")
    add()
    if conc["wall_s"] < serial["wall_s"]:
        why = ("the pool processes the 8 uploads in parallel, so they finish faster "
               "than one after another")
    else:
        why = "the files queue behind each other"
    add(f"All 8 concurrent uploads reached COMPLETED: "
        f"{all(s == 'COMPLETED' for s in conc['statuses'])}. "
        f"Concurrent wall time is {conc['wall_s'] / serial['wall_s']:.2f}x the serial "
        f"wall time ({why}).")
    add()

    # --- profiles ------------------------------------------------------------
    for name in ("kml_1000", "kml_10000"):
        prof = proc["profile"][name]
        overhead = prof["process_s"] / proc["rss"][name]["process_s"]["median"]
        add(f"## cProfile: `app.pipeline.process_file` on `{name}`")
        add()
        add(f"Profiled wall time {fmt(prof['process_s'])} s, "
            f"{overhead:.2f}x the unprofiled pipeline run "
            f"({fmt(proc['rss'][name]['process_s']['median'])} s). "
            "Top 12 by cumulative time.")
        add()
        add("| # | function | cumulative (s) | per-call (s) | calls | own time (s) |")
        add("| ---: | --- | ---: | ---: | ---: | ---: |")
        for index, row in enumerate(prof["top12"], 1):
            add(f"| {index} | `{short_site(row['name'])}` | {fmt(row['cumulative_s'])} | "
                f"{row['per_call_s']:.6f} | {row['ncalls']:,} | "
                f"{fmt(row['tottime_s'])} |")
        add()

    # --- tracemalloc ---------------------------------------------------------
    tm = proc["tracemalloc_10k"]
    rss_10k_peak = proc["rss"]["kml_10000"]["peak_rss_bytes"]["median"]
    add("## tracemalloc, `kml_10000`")
    add()
    add(f"Peak Python-allocated memory during `process_file`: "
        f"**{mb(tm['peak_bytes'])} MB**, against a {mb(rss_10k_peak)} MB "
        f"RSS peak, so most of the live memory sits in C extensions ({extensions}) "
        "that tracemalloc cannot see. Top 8 allocation sites by live bytes "
        "at the largest snapshot taken during processing.")
    add()
    add("| bytes | count | site | code |")
    add("| ---: | ---: | --- | --- |")
    for entry in tm["top"]:
        site = short_site(entry["trace"][0])
        code = short_site(entry["trace"][1]) if len(entry["trace"]) > 1 else ""
        add(f"| {entry['size']:,} | {entry['count']:,} | `{site}` | `{code}` |")
    add()

    # --- scaling -------------------------------------------------------------
    add("## Scaling with feature count")
    add()
    add("Median HTTP end-to-end times from the table above, compared against feature "
        "count. A ratio above 1.0 in the last column would mean worse than linear.")
    add()
    add("| fixture | features | e2e (s) | ms per feature | features x | time x | "
        "time x / features x |")
    add("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    previous = None
    for name in ("kml_100", "kml_1000", "kml_10000"):
        feats = manifest[name]["features"]
        elapsed = http["fixtures"][name]["e2e_s"]["median"]
        if previous is None:
            add(f"| `{name}` | {feats:,} | {fmt(elapsed)} | "
                f"{elapsed * 1000 / feats:.3f} | - | - | - |")
        else:
            p_feats, p_time = previous
            ratio = (elapsed / p_time) / (feats / p_feats)
            add(f"| `{name}` | {feats:,} | {fmt(elapsed)} | "
                f"{elapsed * 1000 / feats:.3f} | {feats / p_feats:.0f}x | "
                f"{elapsed / p_time:.2f}x | {ratio:.2f} |")
        previous = (feats, elapsed)
    add()

    # --- conclusion ----------------------------------------------------------
    prof = proc["profile"]["kml_10000"]["top12"]
    total = proc["profile"]["kml_10000"]["process_s"]
    read_row = find(prof, "(_read_kml)")
    # (prepare) only costs anything once the batched transform exists; older profiles
    # top out before it, so it is optional here.
    prepare_row = find(prof, "(prepare)", default={"cumulative_s": 0.0})
    measure_row = find(prof, "(measure)")
    build_row = find(prof, "(_build_payload)")
    rest = (build_row["cumulative_s"] - read_row["cumulative_s"]
            - prepare_row["cumulative_s"] - measure_row["cumulative_s"])
    to_store = total - build_row["cumulative_s"]

    add("## Where the time goes")
    add()
    add(f"Profiled `process_file` on the 10,000-feature file took {fmt(total)} s. "
        "The three biggest cost centres:")
    add()
    parts = [f"`ElementTree.parse` ({fmt(find(prof, 'ElementTree.py')['cumulative_s'])} s)"]
    coords_row = find(prof, "(_parse_coordinates)", default=None)
    if coords_row:
        parts.append("coordinate parsing "
                     f"(`_parse_coordinates` {fmt(coords_row['cumulative_s'])} s)")
    parts.append(f"property extraction (`_properties_from_placemark` "
                 f"{fmt(find(prof, '(_properties_from_placemark)')['cumulative_s'])} s)")
    add(f"1. **Reading the KML**, `app/geo/readers.py` - {fmt(read_row['cumulative_s'])} s "
        f"cumulative ({read_row['cumulative_s'] / total * 100:.0f}% of the run): "
        + ", ".join(parts[:-1]) + " and " + parts[-1] + ". "
        "The layer extent is folded in here while the coordinates are parsed.")
    reproject = prepare_row["cumulative_s"] + measure_row["cumulative_s"]
    if prepare_row["cumulative_s"]:
        add(f"2. **Reprojecting and measuring**, {fmt(reproject)} s: "
            "`Projector.prepare` pushes every coordinate "
            f"of the layer through pyproj in one call "
            f"({fmt(prepare_row['cumulative_s'])} s), then `measure` walks the arrays "
            f"with the shoelace formula ({fmt(measure_row['cumulative_s'])} s). "
            "No geometry library runs per feature.")
    else:
        add(f"2. **Reprojecting and measuring**, {fmt(reproject)} s: "
            f"`measure` builds each geometry, projects it through shapely and takes "
            f".area or .length ({fmt(measure_row['cumulative_s'])} s cumulative).")
    add(f"3. **Assembling and storing the document**, `app/pipeline.py` "
        f"(`_build_payload`) minus the two above: about {fmt(rest)} s for the summary "
        "totals and the per-feature list that becomes the "
        f"{http['measurements_10k']['bytes']:,}-byte JSON document, plus "
        f"{fmt(to_store)} s for the status updates and `db.save_measurements`.")
    add()
    rss_10k = proc["rss"]["kml_10000"]
    growth_10k_mb = (rss_10k["peak_rss_bytes"]["median"]
                     - rss_10k["baseline_rss_bytes"]["median"]) / 1_000_000
    add("Read once against the scaling table: no part of the pipeline grows faster "
        "than the feature count. Per-feature cost falls from "
        f"{http['fixtures']['kml_100']['e2e_s']['median'] * 1000 / 100:.3f} ms at 100 "
        f"features to {http['fixtures']['kml_10000']['e2e_s']['median'] * 1000 / 10000:.3f} ms "
        "at 10,000 because the fixed per-file cost (CRS resolution, import-time work "
        "already paid, one document write) is spread over more features. Memory grows "
        f"linearly: {growth_10k_mb:.1f} MB "
        f"of growth for 10,000 features, about "
        f"{growth_10k_mb * 1_000_000 / rss_10k['features'] / 1000:.1f} KB per feature, "
        f"over a "
        f"{mb(rss_10k['baseline_rss_bytes']['median'])} MB interpreter baseline.")
    add()
    if conc["wall_s"] < serial["wall_s"]:
        add("Concurrency helps: the dispatcher hands each file to the process pool, "
            f"so 8 simultaneous uploads take {conc['wall_s']:.2f} s wall against "
            f"{serial['wall_s']:.2f} s serially.")
    else:
        add("Concurrency does not help much: one worker thread drains the queue, so "
            f"8 simultaneous uploads take {conc['wall_s']:.2f} s wall against "
            f"{serial['wall_s']:.2f} s serially.")
    add()
    add("Not measured here: RSS of the serving uvicorn process itself while requests "
        "run [not measured], disk write cost of the upload separated from network "
        "[not measured], and any allocation inside C extensions "
        f"({extensions}) which tracemalloc cannot see [not measured].")
    add()

    # --- baseline comparison -------------------------------------------------
    if base_http is not None and base_proc is not None:
        add("## Baseline to final (median against median)")
        add()
        add(f"Left column: the medians in `{args.baseline}/http.json` and "
            f"`process.json`, the run behind `BASELINE.md`. Right column: this run. "
            "Same fixtures, same harness, same machine. The end-to-end noise bands "
            "from `AB_PIPELINE.md` (±5% on kml_1000, ±4% on kml_10000, ±11% on "
            "shp_1000) apply to the e2e rows; a delta inside the band is not signal. "
            "The GET rows are sub-millisecond and move by tenths of a millisecond "
            "between runs, and `AB_EDGE.md` treats a few milliseconds of drift on "
            "these endpoints as noise.")
        add()
        add("| metric | fixture | baseline | final | delta |")
        add("| --- | --- | ---: | ---: | ---: |")

        def row(metric: str, fixture: str, b: float, f: float, digits: int = 3) -> None:
            add(f"| {metric} | {fixture} | {fmt(b, digits)} | {fmt(f, digits)} | "
                f"{delta(b, f)} |")

        row("cold start (s)", "-", base_http["cold_start_s"]["median"],
            http["cold_start_s"]["median"])
        for name in ORDER:
            row("upload latency (ms)", f"`{name}`",
                base_http["fixtures"][name]["upload_ms"]["median"],
                http["fixtures"][name]["upload_ms"]["median"], 2)
        for name in ORDER:
            b = base_http["fixtures"][name]["e2e_s"]["median"]
            f = http["fixtures"][name]["e2e_s"]["median"]
            note = delta(b, f)
            if name in NOISE_BAND:
                inside = abs(f - b) / b <= NOISE_BAND[name]
                note += " (inside noise)" if inside else " (beyond noise)"
            add(f"| e2e HTTP (s) | `{name}` | {fmt(b)} | {fmt(f)} | {note} |")
        for name in ORDER:
            row("in-process e2e (s)", f"`{name}`",
                base_proc["inproc"][name]["e2e_s"]["median"],
                proc["inproc"][name]["e2e_s"]["median"])
        for name in ORDER:
            row("pipeline only (s)", f"`{name}`",
                base_proc["rss"][name]["process_s"]["median"],
                proc["rss"][name]["process_s"]["median"])
        for name in ORDER:
            row("GET file info (ms)", f"`{name}`",
                base_http["fixtures"][name]["info_ms"]["median"],
                http["fixtures"][name]["info_ms"]["median"], 2)
        row("measurements GET (ms)", "`kml_10000`",
            base_http["measurements_10k"]["ms"]["median"],
            http["measurements_10k"]["ms"]["median"], 2)
        row("measurements bytes", "`kml_10000`",
            base_http["measurements_10k"]["bytes"],
            http["measurements_10k"]["bytes"], 0)
        for name in ORDER:
            row("peak RSS (MB)", f"`{name}`",
                base_proc["rss"][name]["peak_rss_bytes"]["median"] / 1_000_000,
                proc["rss"][name]["peak_rss_bytes"]["median"] / 1_000_000, 1)
        for name in ORDER:
            feats = manifest[name]["features"]
            b = feats / base_proc["rss"][name]["process_s"]["median"]
            f = feats / proc["rss"][name]["process_s"]["median"]
            add(f"| pipeline features/s | `{name}` | {b:,.0f} | {f:,.0f} | "
                f"{delta(b, f)} |")
        for name in ORDER:
            feats = manifest[name]["features"]
            b = feats / base_http["fixtures"][name]["e2e_s"]["median"]
            f = feats / http["fixtures"][name]["e2e_s"]["median"]
            add(f"| HTTP features/s | `{name}` | {b:,.0f} | {f:,.0f} | "
                f"{delta(b, f)} |")
        row("8-way concurrency wall (s)", "concurrent",
            base_http["concurrency"]["concurrent"]["wall_s"],
            conc["wall_s"])
        row("8-way concurrency wall (s)", "serial",
            base_http["concurrency"]["serial"]["wall_s"], serial["wall_s"])
        add()

    target = Path(args.out)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
